[pytest]
DJANGO_SETTINGS_MODULE = trocajusta.settings
python_files = tests.py test_*.py *_tests.py
markers =
    unit: Executa apenas os testes unitários (lógica de negócios/services).
    functional: Executa apenas os testes funcionais (views e fluxo HTTP).
