# Generated by Django 5.2.14 on 2026-05-22 23:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
                ('slug_busca', models.SlugField(max_length=60, unique=True, verbose_name='Slug de Busca')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de Email')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('status_conta', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('pendente_verificacao', 'Pendente de Verificação')], default='pendente_verificacao', max_length=20, verbose_name='Status da Conta')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_produto', models.CharField(max_length=100, verbose_name='Título do Produto')),
                ('descricao_detalhada', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco_solicitado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço Solicitado')),
                ('status_publicacao', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('vendido', 'Vendido'), ('bloqueado_fraude', 'Bloqueado por Fraude')], default='ativo', max_length=20, verbose_name='Status da Publicação')),
                ('data_postagem', models.DateTimeField(auto_now_add=True, verbose_name='Data de Postagem')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL, verbose_name='Anunciante')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='core.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'db_table': 'anuncios',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_categoria', models.CharField(max_length=50, verbose_name='Motivo/Categoria')),
                ('detalhes_denuncia', models.TextField(verbose_name='Detalhes da Denúncia')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.anuncio', verbose_name='Anúncio Denunciado')),
                ('perfil_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/imagens/', verbose_name='Imagem do Produto')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.anuncio', verbose_name='Anúncio')),
            ],
            options={
                'verbose_name': 'Imagem do Anúncio',
                'verbose_name_plural': 'Imagens dos Anúncios',
            },
        ),
    ]
