# Generated by Django 5.2.14 on 2026-06-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(choices=[('charqueadas', 'Charqueadas'), ('sao_jeronimo', 'São Jerônimo'), ('triunfo', 'Triunfo'), ('arroio_dos_ratos', 'Arroio dos Ratos'), ('butia', 'Butiá'), ('minas_do_leao', 'Minas do Leão')], default='charqueadas', max_length=20, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua e Bairro (Apenas para Verificação)'),
        ),
    ]
